# highlighter: pygments
# Site settings
title: Mickir的魔法笔记
email: zyeoman@163.com
description: 每一个魔法师都要有一本魔法笔记!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mickir.me" # the base hostname & protocol for your site
enforce_ssl: mickir.me
github_username:  zYeoman
favicon: "/favicon.ico"

# Build settings
permalink: /blog/:title.html   #博文的固定链接
paginate: 10
author:                                     #自定义常量
  name: Mickir
  email: zhuangyw.thu@gmail.com
  link: https://mickir.me/
  weibo: http://weibo.com/mickir
  github: https://github.com/zYeoman

leancloud:
  enable: true
  app_id: xYnmPhrQu3YUQ28Ywk2qEfIp-gzGzoHsz
  app_key: ijsCplpAyUiEzXD36KkOFwHU

analytics:
  google: "UA-96052060-1"

exclude: [LICENSE, CNAME, README.md, .gitignore, Rakefile.rb]

avatar: /head.jpg

timezone: Asia/Shanghai

plugins:
    - jekyll-paginate
    - jemoji
    - jekyll-mentions
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-sitemap

markdown: kramdown
kramdown:
  hard_wrap:  true
  parse_block_html: true
