# highlighter: pygments
# Site settings
title: Mickir的魔法笔记
email: yeo@mickir.me
description: 每一个魔法师都要有一本魔法笔记!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mickir.me" # the base hostname & protocol for your site
github_username:  zYeoman
favicon: "/favicon.ico"

# Build settings
permalink: /blog/:title.html   #博文的固定链接
author:                                     #自定义常亮
  name: 庄永文
  email: zhuangyw.thu@gmail.com
  link: http://mickir.me/
  weibo: http://weibo.com/mickir
  github: http://github.com/zYeoman

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址

exclude: [LICENSE, CNAME, README.md, .gitignore, Rakefile.rb]

avatar: /head.jpg

timezone: CN

gems:
      - jemoji
      - jekyll-gist
