# Build settings
highlighter: pygments
permalink: blog/:year/:month/:title.html
paginate: 6
paginate_path: page/:num
exclude: [LICENSE, CNAME, README.md, .gitignore, Rakefile.rb]


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "tables", "underline", "lax_spacing", "html_toc"]

# life collections
collections:
  life:
    output: true

# Site settings
blog:
  name: Yeoman Zhuang
  title: Mickir's Blog
  description: 有很多这样的时刻。你惊心动魄，而世界一无所知。你翻山越岭，而天地寂静无声。人生说到底，是一场一个人的战争。
  url: "http://mickir.xyz" # the base hostname & protocol for your site
  duoshuo: mickir
author:
  name: Yeoman Zhuang                                    # 作者名称
  email: zyeoman@163.com
  weibo: http://weibo.com/mickir # 微博地址
  github: http://github.com/zyeoman                        # GitHub地址
